### ISSUE TITLE
NPE with Junit5, SLF4J (log4j2) and Spring Boot Test

### ISSUE THREAD

**Issue by vguna** [haasted/TestLogCollectors#6]
Just tried the following:

```
@ExtendWith(SpringExtension.class)
@SpringBootTest(
        classes = { Bla.class },
        webEnvironment = WebEnvironment.NONE)
@ActiveProfiles("test")
@LogCollectorExtension
public class FooTest {

...
    Logger logger = LoggerFactory.getLogger(Foo.class);
    JUnit5LogCollector collector = new JUnit5LogCollector(logger);
...

    @Test
    public void testFoo() {

        doSomethingWithFoo();

        // NPE happens here
        collector.getLogs().stream().forEach(log -> System.out.println(log));
    }
...
}
```

It dies with:

```
java.lang.NullPointerException
	at dk.bitcraft.lc.Log4j2Collector.getResult(Log4j2Collector.java:41)
	at dk.bitcraft.lc.JUnit5LogCollector.getLogs(JUnit5LogCollector.java:28)
	at com.acme.FooTest.testFoo(FooTest.java:131)
```

Seems like the `appender` in `Log4j2Collector` isn't properly initialized. Maybe somehow `setup()`  isn't called properly?

**Comment by rbachlec** [comment]
Same problem here.

I found out that the _@LogCollectorExtension_ annotation is ignored as soon as there is another _@ExtendWith_ annotation. That means that the collector is not initialized.

That would not be that big problem if _@JUnit5LogCollectorExtension_ wouldn't be package scoped so that it could be used directly with a present _@ExtendWith_ annotation.

**Comment by sfdc-slumos** [comment]
Anyone have a workaround for this?
